config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "statuses#index"

  get '/statuses', to: 'statuses#index'
  post '/statuses', to: 'statuses#create' 
  get '/statuses/new(/:replied_id)', to: 'statuses#new', as: 'status_new' 
  get '/statuses/:id', to: 'statuses#show', as: 'status'
  get '/statuses/:id/edit', to: 'statuses#edit', as: 'status_edit'
  patch '/statuses/:id', to: 'statuses#update' 
  delete '/statuses/:id', to: 'statuses#destroy'

  get '/users', to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/medium.rb
require 'addressable/uri'

class Medium < ApplicationRecord
  belongs_to :status

  validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp }, allow_blank: true

  enum :kind, image: 0, video: 1
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
  belongs_to :replied, class_name: 'Status', optional: true
  has_many :media, dependent: :destroy  
  has_many :replies, class_name: 'Status', foreign_key: :replied_id, dependent: :destroy
  accepts_nested_attributes_for :media, limit: 4, allow_destroy: true 
  accepts_nested_attributes_for :replies, allow_destroy: true

  validates :body, presence: true, length: { maximum: 300 }
  validates :media, length: { maximum: 4, message: "Status can have a maximum of 4 media" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :statuses
  has_many :followers_follow, class_name: 'Follow', foreign_key: :followed_id 
  has_many :followers, through: :followers_follow, source: :follower
  has_many :following_follow, class_name: 'Follow', foreign_key: :follower_id
  has_many :followings, through: :following_follow, source: :followed

  accepts_nested_attributes_for :statuses, allow_destroy: true
  
  validates :handle, presence: true, #"check if the value is either nil or a blank string, that is, a string that is either empty or consists of whitespace" [Rails Guides]
            length: { in: 4..12 }, 
            uniqueness: true, 
            format: {
              with: /\A\w+\z/,
              message: "only allows number, letters and underscore"
            }

  validates :display_name, presence: true, length: { maximum: 30 }
  validates :bio, length: { maximum: 300 }
  validates :born_at, presence: true
  validate :born_at do
    errors.add(:born_at, 'must be at least 13') unless born_at.nil? || born_at < Date.current - 13.years
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  
  def index 
    @all_status = Status.all
  end 

  def show 
    @status = Status.find(params[:id])
  end 

  def new 
    
    if params[:replied_id]
      @status = Status.new(replied_id: params[:replied_id])
    else
      @status = Status.new 
    end
    
    4.times { @status.media.build }
  end

  def create

    @status = Status.new(status_params)
    @user = User.new(handle: 'handlename', display_name: 'handle name', bio: nil, born_at: Date.current - 20.years)
    @user.save

    return redirect_to @status if @status.save

    render :new, status: :unprocessable_entity

  end 

  def edit 
    @status = Status.find(params[:id])

  end 

  def update 
    @status = Status.find(params[:id])

    return redirect_to @status if @status.update(status_params)
    render :edit, status: :unprocessable_entity
  end 

  def destroy 
    @status = Status.find(params[:id])
    @status.destroy 

    redirect_to statuses_path
  end 

  private 

  def status_params 
    params.require(:status).permit(:id, :body, :user_id, :replied_id, media_attributes: [:kind, :url, :id])
  end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for status do |form| %>

  <% if status.errors.any? %>
    <div id='error_message'>
      <p><%= status.errors.full_messages.join(' / ') %></p>
    </div>
  <% end %>

  <% if status.replied_id %>
    <%= form.hidden_field :replied_id, value: status.replied_id  %>
  <% end %>

  <div>
    <h3>User</h3>
    <%= form.label "Choose user"%>
    <%= form.collection_select :user_id, User.all, :id, :handle, prompt: true%> 
  </div>

  <div>
    <h3>Status</h3>
    <%= form.label "Type status"%> <br>
    <%= form.text_area :body, size: "50x10" %>
  </div>

  <div>
    <h3>Media</h3>
    <%= form.fields_for :media do |media_form| %>
      <%= media_form.label :kind%>
      <%= media_form.text_field :kind%> <br>

      <%= media_form.label :url%> 
      <%= media_form.text_field :url%> <br><br>
    <% end %>
      
  </div>   

  <div>
    <%= form.submit "Save"%>
  </div> 

<% end %>

app/views/statuses/edit.html.erb
<h1> Edit status </h1>

<%= render 'form', status: @status %>

app/views/statuses/index.html.erb
<!--Dashboard/Index-->
<h1> Dashboard </h1>

<div>
  <%= link_to "Add new status", status_new_path %>
</div>

<% if @all_status.empty? %>
  <h3>Dashboard is empty</h3>
<% else %> 
  <table>
    <thead>
      <th>User</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tr>
      <td></td> 
    </tr>
    <% @all_status.each do |status| %>
      <tr>
        <td><%= status.user.display_name %></td>
        <td> <%= status.body %> </td>
        <td><%= link_to "Details", status_path(status)%></td>
        <td><%= link_to "Delete", status_path(status), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></td> <!--actions-->
        <td><%= link_to "Reply", status_new_path(status)%></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/statuses/new.html.erb
<h1> Add new status </h1>

<%= render 'form', status: @status %>

app/views/statuses/show.html.erb
<h1> Status detail </h1>

<p><%= @status.user.display_name %></p>
<p><%= @status.body %></p>
<h5>Media</h5>
<% @status.media.each do |medium| %>
  <p><%= medium.kind %></p>
  <p><%= medium.url %></p>
<%end%>


<%= link_to 'Edit status', status_edit_path(@status)%>
<%= link_to 'Back', root_path %>